### ISSUE TITLE
TOC cannot jump when using unicode in title

### ISSUE THREAD

**Issue by QiuMP** [remarkjs/remark-toc#17]
## Bug report
When I use unicode characters in title, the links of toc does not work.

## Reproduce
Type some unicode characters in title.

```
# TOC
...
# 日本語
```

Then click the link has no effect.

**Comment by wooorm** [comment]
@QiuMP Sorry for the slow response.

How do you mean it’s not working? We’re using [`github-slugger`](https://github.com/Flet/github-slugger) under the hood, and that should create identifiers just like GitHub.
If it “isn’t clickable”, that’s either a bug there, and the issue should be reported there.
Or, if you’re not viewing on GitHub, you can add your own IDs to headings by settings them on every heading as `.data.hProperties.id = something` yourself.
