### ISSUE TITLE
Content between TOC and next header gets removed

### ISSUE THREAD

**Issue by pascal-mugnier-sonarsource** [remarkjs/remark-toc#18]
If you have content between the TOC header and the next header, the plugin will remove it.

Exemple:

```
## Table of Contents

Some text here...

## First title
```

In this example, `Some teext here...` will get removed.

I think this can be fixed by changing this line:

`node.children.slice(result.index)`

to

`node.children.slice(result.endIndex)`

**Comment by wooorm** [comment]
Why do you think that’s a bug? IMO it’s a feature 🤷‍♂️ What else would you like to put in a toc?

**Comment by pascal-mugnier-sonarsource** [comment]
I think I was not clear enough...
Let's say you have this markdown:

```
## Table of Contents

This is my intro text, explaining what is on this page, lorem ipsum dolor sit amet.

## Title One
### Sub title A

Some text from Sub title A

### Sub title B

Some text from Sub title B
```

I would expect, with the ToC plugin, to end up with something like this:

```
## Table of Contents
## Title One
### Sub title A
### Sub title B

This is my intro text, explaining what is on this page, lorem ipsum dolor sit amet.

## Title One
### Sub title A

Some text from Sub title A

### Sub title B

Some text from Sub title B
```

But I end up with:


```
## Table of Contents
## Title One
### Sub title A
### Sub title B

## Title One
### Sub title A

Some text from Sub title A

### Sub title B

Some text from Sub title B
```

The intro text gets remove.

**Comment by wooorm** [comment]
Hmm, from all the tables of contents I’ve seen I think that they only house a list of the content. I don’t think I’ve seen alternative content being used.

Why not go with:

```markdown
...

This is my intro text, explaining what is on this page, lorem ipsum dolor sit amet.

## Table of Contents

* Title One
  * Sub title A
  * Sub title B

## Title One
### Sub title A

Some text from Sub title A

### Sub title B

Some text from Sub title B

...
```

**Comment by pascal-mugnier-sonarsource** [comment]
Well, this can be done this way of course. But I still think this is a bug, and it can be fixed quite easily.

Paragraphs between ToC and first title should not simply disappear IMO.

**Comment by wooorm** [comment]
Currently we’re looking for a heading and replacing the whole content of that “section”. The same is done for `remark-usage` and `remark-license`. It’s used throughout the ecosystem.

Alternatively, we could look for comments, called “ranges”. See [`mdast-zone`](https://github.com/syntax-tree/mdast-zone) for more info. I believe that would be able to do what you want. I’m sure a PR to [`BarryThePenguin/mdast-util-toc`](https://github.com/BarryThePenguin/mdast-util-toc) for that support would be OK (this plugin is just a small wrapper around that).

**Comment by wooorm** [comment]
Feel free to open a PR there if you’d like to add this new feature.
I don’t see your report as a bug though.

**Comment by florianwalther-private** [comment]
I have the same problem right now. I want to have some intro text _after_ the ToC without its own heading. Is there a way to achieve this?

**Comment by florianwalther-private** [comment]
My workaround, for now, is to add an "Intro" header to the intro section, let remark-toc skip it:

```
.use(remarkToc, {skip: 'Intro'})
```

And then I hide the h2 tag with CSS (I wanna keep the empty space):

```

.blogPostContainer :global(h2#intro) {
    visibility: hidden;
}
```

**Comment by wooorm** [comment]
The same response (https://github.com/remarkjs/remark-toc/issues/18#issuecomment-406615797) still holds.

**Comment by dereckmezquita** [comment]
@pascal-mugnier-sonarsource I created my won function to use as a plugin and shared it here: https://github.com/remarkjs/remark-toc/issues/40#issuecomment-1721880079
