### ISSUE TITLE
Command line usage

### ISSUE THREAD

**Issue by RichardLitt** [remarkjs/remark-toc#19]
I'd like to be able to check that a TOC exists and to create it appropriately as part of an npm script. See [this PR](https://github.com/orbitdb/orbit-db/pull/428#issuecomment-412358372) for more.

`remark-validate-links` provides this functionality; is there a lot that needs to be done to enable this for `remark-toc`?

**Comment by RichardLitt** [comment]
That sums it up, yeah. I think I realized that this was more effort than it is worth for what I need - `remark-toc` does what I want without also adding a linter to it. The thing you pointed to would work, but I'd have to extract it from that module, which is more effort than gain for me at the moment.

So, thank you. :)

**Comment by wooorm** [comment]
Yeah, I was thinking along the same lines. We could create a new rule though, but yup, it may be more work than it’s worth!
