### ISSUE TITLE
bug: latest version of remark-toc (and subsequently remark-cli) causing weird spacing bug

### ISSUE THREAD

**Issue by niftylettuce** [remarkjs/remark-toc#20]
after upgrading to `remark-cli@6.0.0` I noticed that the README automatic TOC was getting formatted improperly - specifically there were line breaks on indented list items in the TOC which causes awkward formatting

![screen shot 2018-10-31 at 12 22 10 am](https://user-images.githubusercontent.com/523141/47767768-2565ab00-dca3-11e8-93b8-26ea0bdb0b0c.png)

![screen shot 2018-10-31 at 12 23 16 am](https://user-images.githubusercontent.com/523141/47767776-2dbde600-dca3-11e8-8fd7-aa05109ffd59.png)

**Comment by wooorm** [comment]
@niftylettuce Are you on the latest `remark-toc` as well?

**Comment by niftylettuce** [comment]
upgrading that fixed it, however I ran into another issue and will be filing it now
