### ISSUE TITLE
Add ability to exclude certain headings

### ISSUE THREAD

**Issue by jaydenseric** [remarkjs/remark-toc#22]
It would be great if an array of headings to exclude from the ToC was an option.

[`jsdoc-md`](https://github.com/jaydenseric/jsdoc-md) generates API docs where members can be infinitely nested. Each member can have `See` and `Examples` subheadings. These really bloat the ToC, and can't be removed using the `maxDepth` options because they can potentially appear at any depth.

An example ToC: https://github.com/jaydenseric/graphql-react#table-of-contents

**Comment by wooorm** [comment]
I think it’s an OK idea, and would probably accept a PR for it.

However, typically you could solve this by fixing the document outline, or by using [lower-level headings such as here](https://github.com/unifiedjs/unified), which has the added benefit of being less intrusive for someone reading the readme IMO

**Comment by jaydenseric** [comment]
Not sure why this was closed, as `remark-toc` still can't skip headings; the new `skip` option that has been added to `mdast-util-toc` is not supported yet here.
