### ISSUE TITLE
Support for custom elements

### ISSUE THREAD

**Issue by thesayyn** [remarkjs/remark-toc#25]
### Subject of the feature
Currently, the links rendered as  HTML anchor tags (a), there be should an option for let user specify a custom template to render the anchor links.

### Problem
In our case, we are creating a lot of documentation files from markdown files, of course with TOC. Also, these documents are served as HTML files in a random path on the server. (In a single page application with innerHTML).

Currently generated documents have anchor links without the base path of the current link, so when I click the TOC Item it redirects me to the main page because the generated links do not have a base path which is base of the problem.  

We cannot use the prefix option because we are serving the documents in random paths.
### Expected behaviour
Should be able to specify a custom template for generated anchor links.

### Alternatives
We have a workaround which is simply replacing the anchor tags with a custom one.  

Note: I don't know if this is the right place to create this issue since this plugin has nothing to do with HTML output. Thanks

**Comment by thesayyn** [comment]
Anyone running into this problem my solution is 


```typescript 
const remark = require("remark");
const remarkHtml = require("remark-html");
const remarkToc = require("remark-toc");
const remarkHighlight = require("remark-highlight.js");

function anchor(h: any, node: any) {
  if (!node.url.startsWith("#")) {
    return h(node, "a", { href: node.url, target: '_blank' }, node.children);
  }
  return h(node, "fragment-link", {url: node.url}, node.children);
}

export function renderMarkdown() {
  return function renderMarkdownImpl(content: any) {
    const renderer = remark()
      .use(remarkToc)
      .use(remarkHighlight)
      .use(remarkHtml, {handlers: {link: anchor}});
    return renderer.processSync(content).toString();
  };
}

```

**Comment by wooorm** [comment]
I suggest, first of all, to use remark-rehype and benefit from the rehype ecosystem. There’s a rehype-toc as well. And there are more plugins!

Also: could you provide some input markdown and expected output?

**Comment by thesayyn** [comment]
Of course;

Input:

```md
# Bucket
## Table of contents

## Getting started
Some text about how to start
```

Current output is 
```html
...
<ul>
  <li><a href="#getting-started">Getting started</a></li>
</ul>
```

Suggested output (through configuration)
```html
...
<ul>
  <li><my-custom-link href="#getting-started">Getting started</my-custom-link></li>
</ul>
```

**Comment by wooorm** [comment]
Thanks for clarifying! This project is really meant for Markdown, so it sounds out of scope to me.
I feel this may be something for https://github.com/JS-DevTools/rehype-toc. It already lets you set classes and its possible to use the `customizeTOC` function to accomplish what you want.
