### ISSUE TITLE
Support remark-attr?

### ISSUE THREAD

**Issue by rauschma** [remarkjs/remark-toc#27]
Thanks for this plugin!

Would it be possible to support remark-attr? For example:

```md
## Heading
{#id-of-heading}
```

One conceivable approach is to pick up the IDs of headings after remark-attr and remark-slug did their work. But I don’t know if that is possible.

**Comment by wooorm** [comment]
Hi Alex, welcome! 👋

I just tested it and it works for me. Could you provide more info on how you are using unified?

> One conceivable approach is to pick up the IDs of headings after remark-attr and remark-slug did their work.

Yup, that’s what we do, [here](https://github.com/syntax-tree/mdast-util-toc/blob/beca120e03db0a715b8517248968bf34290ebd1a/lib/search.js#L49).

**Comment by rauschma** [comment]
Oh dear – never mind. I thought I had set the ID of a heading, but I hadn’t. Thanks for your reply – much appreciated!
