### ISSUE TITLE
Update mdast-util-toc dependency to v5

### ISSUE THREAD

**Issue by davidtheclark** [remarkjs/remark-toc#28]
I'm particularly interested in the 5.0.1 bug fix (https://github.com/syntax-tree/mdast-util-toc/releases/tag/5.0.1). This and future fixes to mdast-util-toc can't be enjoyed by remark-toc users without a dependency update.

**Comment by davidtheclark** [comment]
(I probably should have labeled this issue as a bug, rather than a feature request, because the dependency update will fix a bug.)

**Comment by ChristianMurphy** [comment]
PRs are welcome!

**Comment by wooorm** [comment]
@ChristianMurphy, @Rokt33r Either of you interested in working on types, to squeeze it into the major release of updating to [5.0.0](https://github.com/syntax-tree/mdast-util-toc/releases/tag/5.0.0)?

No rush, we can also do it another time!

**Comment by wooorm** [comment]
(also /cc @BarryThePenguin)

**Comment by ChristianMurphy** [comment]
@wooorm I could look into it

**Comment by BarryThePenguin** [comment]
@ChristianMurphy, let me know how you go. Looks like I attempted this a while ago but never submitted a PR 😅

**Comment by ChristianMurphy** [comment]
If you have something ready, or want to work on it go for it!
