### ISSUE TITLE
Add ability to add a class/id to the generated TOC

### ISSUE THREAD

**Issue by ben-harris** [remarkjs/remark-toc#30]
### Subject of the feature

It would be great if we were able to give the created table of contents (TOC) something for it to be identified on the page.

My idea would be to give a class/id as an option which will then be added to the `<ul>` that wraps the TOC. 

### Problem

Our design requires the TOC to be styled differently than the rest of the `<ul>`'s on the page, and currently it's difficult to select the TOC in order to give specific CSS properties to it.

I've tried only selecting the first instance of a `<ul>` in order to select the TOC, but I don't think this is ideal, as you can never be 100% sure the TOC will be the first `<ul>` on the page.

### Expected behavior

When initialising the TOC plugin give an optional option parameter of `id` which will be added to the TOC `<ul>`

`.use(toc, {id: "table-of-contents"})`

```
<ul id="table-of-contents">
  <li></li>
</ul>
```

### Alternatives

Any alternatives/workarounds welcome, there may already be a way to do this that I haven't thought of yet

**Comment by wooorm** [comment]
Hi Ben!

That sounds more like something for html/rehype. Perhaps https://github.com/JS-DevTools/rehype-toc is what you’re looking for. What do you think?

**Comment by ben-harris** [comment]
Ohh wow yeah that does look more like it! Sorry, only just starting to work with remark/rehype and clearly am not fully understanding how they all work together yet! 🤦 

I'll close this feature request, thanks for your help

**Comment by jeanlucaslima** [comment]
If you somehow got here just like me: looking for a way to just change to your local language consider using a `heading`: https://github.com/remarkjs/remark-toc?tab=readme-ov-file#example-a-different-heading
