### ISSUE TITLE
Disabling anchors in TOC headings

### ISSUE THREAD

**Issue by msmsimondean** [remarkjs/remark-toc#31]
### Subject of the feature

Would it be possible to introduce an option for disabling creating anchors for TOC headings.  

### Problem

I'm using remark-toc without adding slugs to headings.  It would be good to be able to generate a TOC that doesn't use anchors/links

### Expected behavior

Input: 

```markdown
# Alpha

## Table of Contents

## Bravo

### Charlie

## Delta
```

Expected Output:

```markdown
# Alpha

## Table of Contents

-   Bravo

    -   Charlie

-   Delta

## Bravo

### Charlie

## Delta
```

**Comment by wooorm** [comment]
Why?

**Comment by wooorm** [comment]
I don’t really see this making sense here!

**Comment by msmsimondean** [comment]
Hi @wooorm.  The background is I have web page I'm rendering (using Vue.js / Nuxt.js) that includes some Markdown rendered to HTML + other information.  I want to include a TOC in the rendered Markdown to show that sections are in the Markdown (it's a README.md rendered as HTML).  The headings in the Markdown, when rendered to HTML, don't have anchors, which I've done on purpose.  Consequently, the headings in the TOC do have links and they point at anchors that don't exist.

**Comment by wooorm** [comment]
Could you `skip` them? https://github.com/syntax-tree/mdast-util-toc#optionsskip

Why do you remove anchors?

**Comment by msmsimondean** [comment]
Hello.  So I want to show all headings in the TOC (all headers at relevant depths) but I don't want to have slugs/links on any of those headings.

**Comment by msmsimondean** [comment]
The Markdown content is README content that I'm showing as part of a large page.  The overall page has it's own headings/anchors that are independent from and possibly conflicting with the Markdown content.  Basically the webpage is about a given piece of software and part of the content of the page (only part of it) is the content of the software's README.md file.

**Comment by wooorm** [comment]
If you’re worried about conflicts, then the `prefix` option can be used: https://github.com/syntax-tree/mdast-util-toc#optionsprefix (although it’s not yet supported here, will work on that)

**Comment by msmsimondean** [comment]
Hi @wooorm.  Support for the `prefix` option would be very handy thanks.  Looks like https://github.com/rehypejs/rehype-sanitize puts `user-content-` on the front of each id value and it'd be handy to be able to add the same `user-content-` prefix via this plugin.  Thanks

**Comment by BarryThePenguin** [comment]
@msmsimondean it looks like support was added in https://github.com/remarkjs/remark-toc/commit/00c466f763eb5a7a451831a862a31f0003e57145

**Comment by wooorm** [comment]
I releases it! See above referenced commit!

**Comment by msmsimondean** [comment]
Thanks very much both!  That's a really quick response
